# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: sofle_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: sofle_left_simple_oled

  - board: nice_nano_v2
    shield: sofle_right
    artifact-name: sofle_right_simple_oled

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk_reset

  - board: nice_nano_v2
    shield: sofle_left nice_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: sofle_left_nice_oled

  - board: nice_nano_v2
    shield: sofle_right nice_oled
    artifact-name: sofle_right_nice_oled
    
  - board: nice_nano_v2
    shield: sofle_right nice_view_adapter dongle_display_view_pro_micro
    artifact-name: sofle_right_nice_oled_dongle
